# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EWL+0ESEtRCV2800tgq/WyQM5q4JDwA8bob5WMY0rc0nyuiCSPO3thD63n6JAmpTTqlBDiYnRawMEPPZY+Y2zl/XoyNFap1925ukzKyidI+gLP12uWrKzHccmpYLGaxcZROMAboqbsCW/4agPN0EeKOUnUlb2o8ObQk9schW2fBstf5rA0GPPKy9Oy3m3YT2q1vwKfTysACaDlgDW7IBaqH+W8OKY3PtZfSFPk3PRZzGQXH4RIb8QVspFHHl4pUABOaILcwjcEe9nQVMtcvk7zPiDVCs7LMoMeqs8aT5kHofVFz83Vwm6wiQT5KW6gD4gnqRSZ7K2N3T22khIZGkGtGxIRZpA6OLCnScZ0MtlhSG+94jarXpE8wLXdN5ypCRyPZd6tD1MPkjyUHDG9U7salFMKv8MnokEkY5rR5J+RDB2os4yQIduzYZfWuaRmZlWVuX5KgBjDzd3+ln/0T/huhSZpe0OBk7A34Wb0fdug79RCOA2xecA+BdRQw71D/6u0X57EWJdn9VChHBT7Lcojf0COagc5ILu8MkbQn/zy3OZC/EEDRyKMjtcWfVvWMC7t0qD5qTHiL/3jnuSNwE0WGAnWgrA8Gq6WrFjphaefOdQ3aYL0H3S4q140Lq2bR09qa2EUSdUFK+1pOuKsJQlsDEnN42K34bbuo3zW9JFj8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
