travis:
  secure:
    BINSTAR_TOKEN: EWL+0ESEtRCV2800tgq/WyQM5q4JDwA8bob5WMY0rc0nyuiCSPO3thD63n6JAmpTTqlBDiYnRawMEPPZY+Y2zl/XoyNFap1925ukzKyidI+gLP12uWrKzHccmpYLGaxcZROMAboqbsCW/4agPN0EeKOUnUlb2o8ObQk9schW2fBstf5rA0GPPKy9Oy3m3YT2q1vwKfTysACaDlgDW7IBaqH+W8OKY3PtZfSFPk3PRZzGQXH4RIb8QVspFHHl4pUABOaILcwjcEe9nQVMtcvk7zPiDVCs7LMoMeqs8aT5kHofVFz83Vwm6wiQT5KW6gD4gnqRSZ7K2N3T22khIZGkGtGxIRZpA6OLCnScZ0MtlhSG+94jarXpE8wLXdN5ypCRyPZd6tD1MPkjyUHDG9U7salFMKv8MnokEkY5rR5J+RDB2os4yQIduzYZfWuaRmZlWVuX5KgBjDzd3+ln/0T/huhSZpe0OBk7A34Wb0fdug79RCOA2xecA+BdRQw71D/6u0X57EWJdn9VChHBT7Lcojf0COagc5ILu8MkbQn/zy3OZC/EEDRyKMjtcWfVvWMC7t0qD5qTHiL/3jnuSNwE0WGAnWgrA8Gq6WrFjphaefOdQ3aYL0H3S4q140Lq2bR09qa2EUSdUFK+1pOuKsJQlsDEnN42K34bbuo3zW9JFj8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
