appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BAi6PXrjoVVnUFlLslaCdow+/J7X8vXQDWhm9ltP4AEQtwRL2FSIFgqsfSBNBRv+Mlg4LnK4hZDx2hBCQdF7vwM3SJqiFKKZwYjGU7qp2YT1gRsg4gx9JLfs3pHEUoK8YFxwtM6Fky5if781HjprctCbf2JozeR2ny8vITSZeDyoC0JTZ2PUD7BvqkhDDNpCcCIMO8YuX4CsgB81cG0c07QUYGAx4Cay+A4niH5fMTMWWnpNrIjJmQO63pAYZTnrIT57pvsV54xpcC8w3soZQEt+ULNXdXnGjsnxiLUi3CKA9Xy91ASvGu5kRFux/iQffNCikW5eyNnKfCdbOU+9whW7CK+wt1toVYWPozhw9PF3Ll5zy5jmWn7pHINbGoAnppMBWhCcbdZR1EaMLtlpL1rYUgkSU3XPPG8QtgSh3u2OgpYTAeBo8+EgUUgt432aPKkkSbi5IP39lkzFcVxArHGiE0rU5AD+yUIjCaAaz1zfUSGXSHdGlbVS0iYbu9exjJAriEOd+Y9V+JRepqLQUbSjHYsLWAZFG69jTD7Un5tBqNN6mjhah1J1KDGKdY1hoDV9HGDfcxutCUQxmm026+Zrpoj5eKMN2XrBQ6fUlFjrOylKXEzD/KXI9Y+PFpcEgDa/JrNx6HVuk9v70C5IJLLgB4Zy2wRQeJkn9A51qxA=}
